# Generated by Django 2.1.5 on 2019-01-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='link',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='имя'),
        ),
    ]
