# Generated by Django 2.1.5 on 2019-01-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20190121_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Ссылка'),
        ),
    ]
