# Generated by Django 2.1.5 on 2019-01-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20190122_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.CharField(max_length=64, null=True, verbose_name='Ссылка'),
        ),
    ]
